BEP1.md
BEP2.md
README.md

In this PR, BEP 1&2 were added.
BEP1 is the general guideline and BEP2 is about tokens on Binance Chain.

Add BEP1&2 proposals

---

BEP9.md

- [BEP-9: Time Locking of Tokens](#bep-9-time-locking-of-tokens)
- [4. Motivation](#4-motivation)
- [5. Specification](#5-specification)
- [5.1 Transactions](#51-transactions)
- [5.1.1 TimeLock](#511-timelock)
- [5.1.2 TimeUnlock](#512-timeunlock)
- [5.1.3 TimeRelock](#513-timerelock)
- [5.1.4 QueryTimeLocks](#514-querytimelocks)
- [5.1.4 QueryTimeLock](#514-querytimelock)
- [6. License](#6-license)
This BEP describes a proposal for a time-locking feature of tokens on the Binance Chain.
BEP-9 Proposal describes functionality to time-lock tokens on the Binance Chain. Such as:
+ TimeLock: TimeLock will transfer locked tokens to a purely-code-controlled escrow account and before the lock time expires, the …

BEP-9: Time Locking of Tokens

---

BEP10.md

- [BEP-10: Registered Types for Transaction Source](#bep-10--registered-types-for-transaction-source)
* [1. Summary](#1-summary)
* [2. Abstract](#2-abstract)
* [3.  Status](#3--status)
* [4. Motivation](#4-motivation)
* [5. Specification](#5-specification)
+ [5.1 Transaction Data Structure](#51-transaction-data-structure)
+ [5.2 Register Process](#52-register-process)
+ [5.3  Registered Source types](#53--registered-source-types)
* [6. License](#6-license)
This BEP describes how to have a better understanding of the origin of a transaction with a special field in a transaction for recording its source.
By adding a field in each transaction message, the origin of any transaction could be tracked. 
This BEP is WIP.
Binance Chain is designed to connect with multiple service providers, and …

[R4R] Add BEP10: Add source of transactions

---

BEP12.md

For tokens on binance chain, recently exchanges tender to use a single address for client deposit and require clients to input memo to identify client account information. 
This causes a lot of problems for both exchange customer support and clients. Clients may be panic when their tokens are missing and exchange supports have to verify the client deposit transactions manually. This is caused by that many users don’t realize that memo is required or they just forget to do that. What’s worse, sometimes their wallets don’t support transaction memo at all.
So we plan to implement a memo check mechanism on binance chain to filter out all transactions which are intend to deposit tokens to exchanges and have no valid memo.
This memo validation can be used for any membership based deposit/charge …

[R4R]BEP12: Introduce customized scripts and transfer memo validation

---

BEP19.md
README.md

This BEP describes a new on-chain match engine, Maker/Taker concepts are introduced to enhance the current periodic auction match algorithm.
On not-so-liquid or highly volatile markets, the classic periodic auction match methodology would result in much worse average trade price to aggressive orders (i.e. Taker orders in the continuous match context), because all the trades would be marked with one final price, instead of the average price of all the waiting orders from the market. This is not friendly to active traders and amateur clients that are more familiar with continuous match markets. This causes extra effort to split aggressive orders and much confusion as Binance DEX matches as fast as continuous matching exchange.

BEP19: Introduce Maker and Taker for Match Engine

---

BEP10.md

The TrustToken issuer uses source 888.
All transactions from our hardware security module will use source 888.
This is because our token issuing transactions begin with hash 888.
Many of our other transaction hashes will also start with 8, but all will use source 888.
[Issue TUSDB-888](https://dex.binance.org/api/v1/tx/888097BB8AEA13E880FFE309C74D07A0495784BEE035F5490264051F9FB67362?format=json)
[Issue TAUDB-888](https://dex.binance.org/api/v1/tx/8883D78BBD2B6328517B74E7770331ADB97A8B6D690D4112173D600D031F816E?format=json)
[Transfer TUSDB-888](https://dex.binance.org/api/v1/tx/8E115B989047DECF5C3D5617DDDDA3E80BDADF16EA9B702B9E36F510C1AD745D?format=json)
Reviewers @huangsuyu

Register TrustToken Source

---

BEP3.md

This BEP is about introducing Hash Timer Locked Contract functions and further mechanism to handle inter-blockchain token peg.
[HTLC](https://en.bitcoin.it/wiki/Hash_Time_Locked_Contracts) has been used for Atomic Swap and cross payment channel for a few years on Bitcoin and its variant blockchains, and also Ethereum. This BEP defines native transactions to support HTLC on Binance Chain, and also proposes the standard infrastructure and procedure to use HTLC for inter-chain atomic swap to easily create and use pegged token, which is called `Atomic Peg`.
Related BEP: https://github.com/binance-chain/BEPs/pull/3

[R4R]BEP3: HTLC and Atomic Peg

---

BEP39.md

BEP-39 requests that `MEMO` data field be added to the `/ws/userAddress` [websocket](https://docs.binance.org/api-reference/dex-api/ws-streams.html#3-transfer).
Currently the `MEMO` field is not being returned on the websocket, which means that services that rely on MEMO to set transaction specifications must then retrieve it from the [Transaction API endpoint](https://docs.binance.org/api-reference/dex-api/paths.html#transaction).
This creates unneccessary burden on the API and slows down the transaction processing.
The solution is to add it to the Transfer Websocket as a data field to stream.

BEP-39: Add MEMO to Transfer WebSocket.

---

BEP67.md
README.md

This BEP describes an enhancement of the Order Expiration.  
Currently orders on Binance Chain will be expired after 3 days. It is better if we could keep some open orders longer so that traders do not need re-create the expired orders every 3 days.  
The solution is to keep orders in the best 500 price level for 30 days rather than 3 days.

BEP-67: Price-based Order Expiration

---

BEP70.md
README.md

BUSD is one of the most popular stable coins in the world, and people are using it to exchange fiat currencies everyday. If token owners can list BUSD trading paris directly, without dependency on BNB trading pairs, on Binance Chain, it will definitely benefit the markets, token owners and traders. 
BEP70 proposes a solution for listing and trading BUSD pairs without explicit dependency on BNB.
With BEP70, we would like to achieve: 
1) Relaxing the restriction of listing, and 
2) Easy channels to exchange BUSD stable coins

BEP70: List and Trade BUSD Pairs

---

BEP_draft_URI.mediawiki

Aim to build the standard of URI for asset transferring on binance-chain.
Once adopted by binance chain clients, it could make transactions on binance-chain more smooth.

BEP-64: BNB Payment URI Scheme

---

BEP2.md
BEP8.md
BEP87.md
BEPx.md

This BEP proposes to reduce the minimum length limit for token symbol on Binance Chain
Currently, the token symbol minimum length is limited to 3. After implementing this BEP, the users are allowed to issue a token with a symbol of 2 characters.
draft
As many users have the requirements to issue a two-character token on Binance Chain, the minimum token symbol length will be changed to 2 in this BEP.
When the issuer sends an issue transaction for issuing BEP2/BEP8 token, the token symbol length must be between 2-8. Here is the comparison of the length check below:
| **Token Type** | **Length Check(Before)** | **Length Check(After)** |
| :------------- | :----------------------- | :---------------------- |
| BEP2 | 3-8 | 2-8 |
| BEP8 | 3-8 | 2-8 |
After the implementation of this BEP, the …

BEP-87: Token Symbol Minimum Length Change

---

BEP84.md
README.md

Currently, if a user wants to issue and bind a BEP2 token with an existing BEP20 token, it has to do a set of complex operations, including issue BEP2 tokens, sending a bind transaction and approving the binding request. The BEP will bring a mechanism to simplify the above process. In the new mechanism, what anyone can do this is just sending a transaction to Binance Smart Chain.

R4R: BEP84 mirror and sync

---

BEP89.md
README.md

- BEP-89: Visual Fork of Binance Smart Chain
- [4. Motivation](#4-motivation)
- [5. Specification](#5-specification)
- [5.1 Fork Hash](#51-fork-hash)
- [5.2 Vanity](#52-vanity)
- [5.3 Vanity](#53-clients)
- [5.4 Backwards Compatibility](#54-backwards-compatibility)
- [6. License](#6-license)
This BEP describes a proposal to enable the chain to display the whole view of validators that on different upcoming forks.  
The four bytes of `Header.Extra[28:32]` will be fulfilled with `NEXT_FORK_HASH`. The `NEXT_FORK_HASH` indicates which fork the signer of this block is going to stay on. By analysing `N` (`N` is the amount of validators) continuous block headers, we are able to know which fork is supported by the …

BEP-89: Visual Fork of Binance Smart Chain

---

BEP82.md

This BEP describes the changes related to the token owner who issued a token on Binance Chain.
Currently, many token-related transactions, such as token listing, minting, burning, etc., can only be proposed by the token owner who can not be changed once the token is issued on Binance Chain.
This BEP proposes the solutions to provide more convenience and flexibility for these transactions.
draft
To reduce the transaction's dependence on the related token’s owner and make the ownership of token changeable, we introduce those solutions as following:
- Providing an entrance to transfer the ownership of a specific token.
- Removing the owner verification when handling some token related transactions.
**TransferOwnership** transaction can transfer ownership of a specific token to another …

BEP-82: token owner changes

---

BEP151.md
README.md

This BEP proposes to securely and smoothly decommission the build-in decentralized exchange on BNB Beacon Chain.
BNB Beacon Chain’s primary focus, its native decentralized application ("dApp") BNB DEX, has demonstrated its low-latency matching with large capacity headroom. With the development of BNB Smart Chain and AMM-based decentralized exchanges running well on it, BNB DEX has less usage and liquidity. After implementing this BEP, the DEX module will be disabled, which will give Beacon Chain more computing power for the future computing and governance focuses.
Draft
BNB Beacon Chain(BC) is a blockchain developed by the BNB Chain community that implements a vision of a decentralized exchange (DEX) for digital assets. The heart of Beacon Chain is a highly performant matching engine …

BEP-151: Decommission Decentralized Exchange on BNB Beacon Chain

---

BEP154.md
BEP173.md
README.md

- [BEP-173: Introduce Text Governance Proposal for BNB Smart Chain](https://github.com/bnb-chain/BEPs/pull/173)
- [2. Status](#2-status)
- [4.1 Introduction](#41-introduction)
- [4.2 How to draft a text proposal](#42-how-to-draft-a-text-proposal)
- [4.3 Governance stage](#43-governance-stage)
- [4.3.1 Deposit stage](#431-deposit-stage)
- [4.3.2 Voting stage](#432-voting-stage)
- [4.3.3 Tallying stage](#433-tallying-stage)
- [4.3.4 Execution stage](#434-execution-stage)
This BEP introduces a text governance proposal for BNB Smart Chain. 
This BEP is a draft.
In some scenarios, the community may need a proposal that does not directly cause any changes, like agreeing to a certain strategy, …

bep173: enable text proposal on BNB Smart Chain

---

BEP126.md

This BEP introduces a fast finality mechanism on the BNB Smart Chain.
BEP-126 Proposal describes a fast finality mechanism to finalize a block, once the block has been finalized, it won't be
reverted forever.
It takes several steps to finalize a block:
1. A block is proposed by a validator and propagated to other validators.
2. Validators use their BLS private key to sign for the block as a vote message.
3. Gather the votes from validators into a pool.
4. Aggregate the BLS signature if its direct parent block has gotten enough votes when proposing a new block.
5. Set the aggregated vote attestation into the extra field of the new block's header.
6. Validators and full nodes who received the new block with the direct parent block's attestation can justify the direct parent block.
7. If …

[WIP] BEP-126: Introduce Fast Finality Mechanism

---

BEP174.md

This BEP introduces a new governance proposal type to manage the set of whitelisted Relayers.  
A Relayer whitelist was introduced recently to the BSC genesis contracts ([PR-198](https://github.com/bnb-chain/bsc-genesis-contract/pull/198)). 
This BEP will improve the management of the relayer whitelist by introducing Relayer Managers, where a Relayer Manager can manage the registration of a single Relayer. 
Managers will be elected and ejected via governance.
This BEP introduces a new governance proposal type to manage Relayer Manager public keys that will be stored in the [`RelayerHub`](https://github.com/bnb-chain/bsc-genesis-contract/blob/71dcd4c409a68a6e084645a9f1f80adecd5a4269/contracts/RelayerHub.sol) genesis contract on BSC.  
Relayer Managers will be able to manage their …

BEP-174: Cross Chain Relayer Management

---

BEP126.md

The liveness of producing blocks and the liveness of finalizing blocks are independent.
Revert the chain liveness to ½*v+ from ⅔*v+.

 BEP-126: revert the chain liveness to ½*v+ from ⅔*v+

---

BEP217.md

<pre>
BEP: 217
Title: Implement EIP3860 Limit and meter initcode
Status: Draft
Created: 2023-3-30
</pre>
- [BEP-217: Implement EIP3860 Limit and meter initcode](#bep-217-implement-eip3860-limit-and-meter-initcode)
- [7. Test Cases](#test-cases)
As part of Shanghai upgrade, EIP-3860: Limit and meter initcode is required to be implemented to BSC.
The change introduces a maximum size limit for initcode (MAX_INITCODE_SIZE = 2 * MAX_CODE_SIZE = 49152). Which extended the EIP-170: Contract code size limit …

BEP217: Implement EIP3860 Limit and meter initcode

---

BEP226.md

<pre>
BEP: 226
Title: Enable EIP-1559 with base fee of 0
Status: Pre-Draft
Created: 2023-04-17
</pre>
- [BEP-226: Enable EIP-1559 with base fee of 0](#bep-226-enable-eip-1559-with-base-fee-of-0)
- [3. Specification](#3-specification)
- [4. Backwards Compatibility](#4-backwards-compatibility)
- [5. License](#5-license)
This BEP introduces [EIP-1559](https://github.com/ethereum/EIPs/blob/master/EIPS/eip-1559.md) headers and transactions to BSC but with base fee set to 0. 
To keep up to date with the latest developments in EVM blockchains it is important to keep the block and transaction structures up to date. New features (such as account abstraction) being introduced
to EVM chains already presuppose EIP-1559 type …

BEP-226: Implement EIP-1559 with base fee of 0

---

BEP227.md

<pre>
BEP: 227
Title: Add BASEFEE opcode
Status: Pre-Draft
Created: 2023-04-17
</pre>
- [BEP-227: Add BASEFEE opcode](#bep-227-add-basefee-opcode)
- [5. Gas cost](#5-gas-cost)
- [7. Test Cases](#7-test-cases)
- [7.1 Nominal case](#71-nominal-case)
- [8. Security Considerations](#8-security-considerations)
- [9. License](#9-license)
Adds an opcode that gives the EVM access to the block's base fee. This BEP is dependent on BEP-226 (EIP-1559 with base fee of 0). 
Add a `BASEFEE (0x48)` that returns the value of the base fee of the current block it is executing in.
The code for this BEP has …

BEP-227: Implement EIP-3198: BASEFEE opcode

---

BEP228.md

<pre>
BEP: 228
Title: Prevent deploying contracts starting with 0xEF
Status: Pre-Draft
Created: 2023-04-17
</pre>
- [BEP-228: Prevent deploying contracts starting with 0xEF.](#bep-228-prevent-deploying-contracts-starting-with-0xef)
- [3. Specification](#3-specification)
- [3.1 Remarks](#31-remarks)
- [4. Rationale](#4-rationale)
- [5. Test Cases](#5-test-cases)
Disallow new code starting with the `0xEF` byte to be deployed. Code already existing in the account trie starting with `0xEF` byte is not affected semantically by this change.
This BEP essentially enables …

BEP-228: Implement EIP-3541: Prevent deploying contracts starting with 0xEF

---

BEP212.md
BEP999.md

Remove gas refunds for `SELFDESTRUCT`, and reduce gas refunds for `SSTORE` to a lower level where the refunds are still substantial, but they are no longer high enough for current "exploits" of the refund mechanism to be viable.
Gas refunds for `SSTORE` and `SELFDESTRUCT` were originally introduced to motivate application developers to write applications that practice "good state hygiene", clearing storage slots and contracts that are no longer needed. However, the benefits of this technique have proven to be far lower than anticipated, and gas refunds have had multiple unexpected harmful consequences:
* Refunds give rise to GasToken. GasToken has benefits in moving gas space from low-fee periods to high-fee periods, but it also has downsides to the network, particularly in exacerbating …

BEP-212: Implement EIP-3529: Reduction in Refunds

---

BEP-230.md

<pre>
BEP: 230
Title: Implement EIP-2929 Gas cost increases for state access opcodes
Status: Draft
Created: 2023-4-19
</pre>
- [BEP-230: Implement EIP-2929 Gas cost increases for state access opcodes](#bep-230-implement-eip-2929-gas-cost-increases-for-state-access-opcodes)
- [7. Test Cases](#7-test-cases)
- [8. Security Considerations](#8-security-considerations)
- [9. License](#9-license)
- [10. Reference](#10-reference)
As part of Berlin upgrade, EIP-2929 Gas cost increases for state access opcodes is required to be implemented to BSC.
Increases gas cost …

BEP-230: Implement EIP-2929 Gas cost increases for state access opcodes

---

BEP231.md

<pre>
BEP: 231
Title: Implement EIP-2930: Optional access lists
Status: Draft
Created: 2023-4-19
</pre>
- [BEP-231: Implement EIP-2930: Optional access lists](#bep-231-implement-eip-2930-optional-access-lists)
- [6. Security Considerations](#6-security-considerations)
- [7. License](#7-license)
- [8. Reference](#8-reference)
As part of Berlin upgrade, EIP-2930: Optional access lists is required to be implemented to BSC.
Adds a transaction type which contains an access list, a list of addresses and storage keys that the transaction plans to access. Accesses outside the list are possible, but become more expensive.
We …

BEP-231: Implement EIP-2930: Optional access lists

---

BEP255.md

<pre>
BEP: 255
Title: Beacon Chain Asset Reconciliation for Security Enhancement
Status: Draft
Created: 2023-07-04
</pre>
- [BEP-255: Beacon Chain Asset Reconciliation for Security Enhancement](#bep-255-beacon-chain-asset-reconciliation-for-security-enhancement)
- [3. Specification](#3-specification)
- [3.1 Asset Reconciliation](#31-asset-reconciliation)
- [3.2 Halt on Reconciliation Error](#32-halt-on-reconciliation-error)
- [4. License](#4-license)
This BEP proposes implementing on-chain asset reconciliation on BNB Beacon Chain to improve security.
As a beacon chain, the BNB Beacon Chain plays a vital role in securing the BNB chain ecosystem. Although some
enhancements have been made to improve cross-chain …

BEP-255: Beacon Chain Asset Reconciliation for Security Enhancement

---

BEPs/BEP-310.md
BEPs/BEP-311.md

<pre>
BEP: 311
Title: Implement EIP-3651: Warm COINBASE
Status: Draft
Created: 2023-10-30
</pre>
- [BEP-311: Implement EIP-3651 Warm COINBASE](#bep-311-implement-eip-3651-warm-coinbase)
As part of Shanghai upgrade, EIP-3651: Warm COINBASE is required to be implemented to BSC.
The `COINBASE` address shall be warm at the start of transaction execution, in accordance with the actual cost of reading that account.
Direct `COINBASE` payments are …

BEP-311: Implement EIP-3651 Warm COINBASE

---

BEPs/BEP-312.md

<pre>
BEP: 312
Title: Announce EIP-6049: Deprecate SELFDESTRUCT
Status: Draft
Created: 2023-10-30
</pre>
- [BEP-312: Announce EIP-6049 Deprecate SELFDESTRUCT](#bep-312-announce-eip-6049-deprecate-selfdestruct)
As part of Shanghai upgrade, EIP-6049: Deprecate SELFDESTRUCT is required to be announced in the BSC community.
This EIP deprecates the `SELFDESTRUCT` opcode and warns against its use. A breaking change to this functionality is likely to …

BEP-312: Announce EIP-6049 Deprecate SELFDESTRUCT

---

BEPs/BEP-342.md

<pre>
BEP: 342
Title: Implement EIP-5656: MCOPY
Status: Draft
Created: 2024-01-15
</pre>
- [BEP-342: Implement Implement EIP-5656: MCOPY](#bep-342-implement-eip-5656-mcopy)
As part of Cancun upgrade, EIP-5656: MCOPY is required to be implemented to BSC.
Provide an efficient EVM instruction for copying memory areas.
Memory copying is a basic operation, yet implementing it on the EVM comes with overhead.
This was recognised and alleviated early …

BEP-342: Implement EIP-5656: MCOPY

---

BEPs/BEP-345.md

<pre>
BEP: 345
Title: Implement EIP-7516: BLOBBASEFEE opcode
Status: Draft
Created: 2024-01-15
</pre>
- [BEP-345: Implement EIP-7516: BLOBBASEFEE opcode](#bep-345-implement-eip-7516-blobbasefee-opcode)
As part of Cancun upgrade, EIP-7516: BLOBBASEFEE opcode is required to be implemented to BSC.
Add a `BLOBBASEFEE (0x4a)` that returns the value of the blob base-fee of the current block it is executing in. It is the identical to …

BEP-345: Implement EIP-7516: BLOBBASEFEE opcode

---

BEPs/BEP-343.md

<pre>
BEP: 343
Title: Implement EIP-1153: Transient storage opcodes
Status: Draft
Created: 2024-01-15
</pre>
- [BEP-343: Implement EIP-1153: Transient storage opcodes](#bep-343-implement-eip-1153-transient-storage-opcodes)
As part of Cancun upgrade, EIP-1153: Transient storage opcodes is required to be implemented to BSC.
This proposal introduces transient storage opcodes, which manipulate state that behaves identically to storage, except that …

BEP-343: Implement EIP-1153: Transient storage opcodes

---

BEPs/BEP-344.md

<pre>
BEP: 344
Title: Implement EIP-6780: SELFDESTRUCT only in same transaction
Status: Draft
Created: 2024-01-15
</pre>
- [BEP-344: Implement EIP-6780: SELFDESTRUCT only in same transaction](#bep-344-implement-eip-6780-selfdestruct-only-in-same-transaction)
As part of Cancun upgrade, Implement EIP-6780: SELFDESTRUCT only in same transaction is required to be implemented to BSC.
This EIP changes the functionality of the `SELFDESTRUCT` opcode. …

BEP-344: Implement EIP-6780: SELFDESTRUCT only in same transaction

---

BEPs/BEP297.md

<pre>
BEP: 297
Title: BSC Native Governance Module
Status: Draft
Created: 2023-10-16
</pre>
- [BEP-297: BSC Native Governance Module](#bep-297-bsc-native-governance-module)
- [4. Motivation](#4-motivation)
- [5. Specification](#5-specification)
- [6. License](#6-license)
Native Governance is incorporating governance logic into the BNB Smart Chain instead of delegating this responsibility to the BNB Beacon Chain. BSC Native Governance is a primary goal for the BNB Chain Fusion. The proposal allows community members to submit proposals directly on the BSC network. Any staking credit holders are allowed to vote on these proposals, and the passed proposals will be executed automatically on the …

BEP-297: BSC Native Governance Module

---

BEPs/BEP-346.md
README.md

<pre>
BEP: 346
Title: Streamline off-chain authentication on Greenfield
Status: Draft
Created: 2024-03-14
</pre>
- [BEP-346: Streamline off-chain authentication on Greenfield](#bep-346-streamline-off-chain-authentication-on-greenfield)
- [5. License](#5-license)
This BEP introduces GNFD2-EDDSA, a simplified off-chain authentication signature verification method. It streamlines the authentication process, reducing developer integration complexity and improving user interaction.
Greenfield is an object storage system with permission management. SP uses an off-chain authentication mechanism to authenticate users from the dApps. For more details, refer to …

BEP-346:Streamline off-chain authentication on Greenfield

---

BEPs/BEP-344.md
BEPs/BEP-381.md
BEPs/assets/BEP-381/benchstat_compare_test
BEPs/assets/BEP-381/ecrecover_benchmark_test
BEPs/assets/BEP-381/p256Verify_benchmark_test

<pre>
BEP: 381
Title: Precompile for secp256r1 Curve Support
Status: Draft
Created: 2024-04-17
</pre>
- [BEP-381: Precompile for secp256r1 Curve Support](#bep-precompile-for-secp256r1-curve-support)
- [4.1.1 Elliptic Curve Information](#411-elliptic-curve-information)
- [4.1.2 Elliptic Curve Signature Verification Steps](#412-elliptic-curve-signature-verification-steps)
- [4.2 Required Checks in Verification](#42-required-checks-in-verification)
- [4.3 Precompiled Contract Specification](#43-precompiled-contract-specification)
- [4.4 Precompiled Contract Gas Usage](#44-precompiled-contract-gas-usage)
- [6. Backwards …

BEP-381: Precompile for secp256r1 Curve Support

---

BEPs/BEP159.md
BEPs/BEP18.md
BEPs/BEP39.md
BEPs/BEP6.md
BEPs/BEP67.md
BEPs/BEP70.md

1.After BC Fusion, BeaconChain was merged into BSC, so BC is no longer needed.
2.There is a [bnbchain docs site](https://docs.bnbchain.org/) refactor, many linkers are broken. Especially, the BC related urls are no longer provided.
3.It is better not to add external urls into BEPs docs.
Based on these points, I think we can simply remove these broken urls.

doc: remove broken doc links of BeaconChain BEPs

---

BEPs/BEP322.md

This API enables MEV data analysts to query bundle information from builders. 
It is particularly useful for MEV data providers who need to analyze market trends and create analytics dashboards. 
For instance, to accurately measure MEV market activity, providers can use this API to display metrics such as 
daily bundle counts and bundles per block in their analytics panels.
Request:
```json
{
"jsonrpc": "2.0",
"method": "mev_bundles",
"params": [
{
"fromBlock": "0x1",
"toBlock": "0x3"
}
],
"id": 1
}
```
Params:
- `fromBlock`: It is hex value of a block number.
- `toBlock`: Either the hex value of a block number OR block tags: "latest", "pending" or nil. Defaults to "latest". It
should be no less than `fromBlock` and less than `fromBlock+100`.
Response:
* Return bundles whose …

feat: bundle data API

---

BEPs/BEP20.md

This interface is used to bind the BEP20 token and BEP2 token(token on BNB Beacon Chain), as Beacon Chain no longer exist, it is totally ok to have BEP20 token without such interface.

Update BEP20 to remove getOwner interface

---

BEPs/BEP-520.md
BEPs/BEP-524.md
README.md

There would be 2 phases to shorten BSC block interval from 3 seconds to 0.75 seconds:
- Phase 1: 3s -> 1.5s
- Phase 2: 1.5s -> 0.75s
TwoPhase strategy is to avoid one big step to reduce it to 0.75s directly, which could be too risky, as the overall infrastructure may not be fully ready to this change.
And it also update some parameters of Phase-1:
- **Epoch**: 2000 -> 1000,  too long epoch would be not good to update the validator set timely
- **GasLimit**: simply prefer 60M over 65M
- **Blob Update Fraction**: it actually have very limited impact to BSC blob gas price, prefer to remove it for simplicity.
- **TurnLength**: some users may be very cautiously toward TX finalization, they would wait for (2/3)*Validators before confirm the transaction. It would be (2/3)*21*32*1.5s = 672 …

BEP-524: short block interval phase two: 0.75 seconds

---

BEPs/BEP-525.md

<pre>
BEP: 525
Title: Validator Dedicated Network And Directed TxPool
Status: Draft
Created: 2025-02-19
Discussions(optional): https://forum.bnbchain.org/t/idea-faster-p2p-network-for-validators/3282
</pre>
- [BEP-525: Validator Dedicated Network](#bep-525-validator-dedicated-network)
* [1. Summary](#1-summary)
* [2. Motivation](#2-motivation)
* [3. Specification](#3-specification)
+ [3.1.Validator Dedicated Network(VDN)](#31validator-dedicated-networkvdn)
+ [3.2.Directional Transactions Broadcast](#32directional-transactions-broadcast)
+ [3.3.Messages](#33messages)
- [Handshake v1](#handshake-v1)
- [ContactInfo v1](#contactinfo-v1)
- [Block v1](#block-v1)
- [RequestBlockByRange v1](#requestblockbyrange-v1)
- [Vote v1](#vote-v1)
- [Transactions v1](#transactions-v1)
* [4. …

BEP-525: update Validator Dedicated Network design

---

BEPs/BEP-520.md

add description for two cases about `Backward Compatibility`
1. Timing Based on Block Numbers
2. Indexing Based on `block.timestamp`

update BEP-520: add two backward compatibility

---

BEPs/BEP-520.md

update BEP-520: fix contract parameter change target:
misdemeanorThreshold, felonyThreshold and felonySlashScope, these 3 parameter belong to system contract `SlashIndicator`, not `BSCValidatorSet `

update BEP-520: fix contract parameter change target

---

BEPs/BEP-520.md
BEPs/BEP-524.md

votingDelay is 0 in bsc mainnet and chapel net , so no need to change.
https://bscscan.com/address/0x0000000000000000000000000000000000002004#readContract
https://testnet.bscscan.com/address/0x0000000000000000000000000000000000002004#readContract

BEP-520 & BEP-524: no need to change votingDelay

---

BEPs/BEP-520.md

1. As the ratio `initialBackOffTime/blockInterval` increases, validators are more likely to delay block time or delay block broadcast. Therefore, restore the initialBackOffTime here.
2. Validators who intentionally delay block mining should be penalized the same way as those absent for in-turn mining.

BEP-520: recover initialBackOffTime and increments the slash count when block delay mined on purpose

---

BEPs/BEP-520.md
BEPs/BEP-524.md

After communicating with the community, it was found that producing 16 consecutive blocks with a 1.5-second block interval extends the duration a validator can continuously control block production, which may worsen the MEV issue.
This PR modifies the turnLength so that after the hard fork, the duration a validator can continuously control block production remains at 12 seconds.
Additionally, the epoch was originally set to a larger value to ensure fair block production rights among validators within an epoch. After reducing turnLength, the epoch is also shortened accordingly, while validators' block production rights remain unchanged.

BEP-520 & BEP-524: reduce epoch length and turn length

---

BEPs/BEP-520.md
BEPs/BEP-524.md

In the first phase, `Blob Target` and `Blob Maximum` will not be reduced to avoid impacting existing users. 
The final values for  these two values in the second phase may be changed after thorough discussions with the community.

BEP-520 & BEP-524: not change Blob Target and Blob Maximum in the first phase

---

BEPs/BEP-520.md

Two updates to BEP-520:
- Increase **initialBackOffTime** from 1 second to 2 seconds
As the block interval decreases, delayed block propagation will lead to more blocks being reorganized each time. To mitigate this, set initialBackOffTime to 2 seconds. It may have some side-effects, especially it encourages "delay broadcast", but at the moment reorg is more crucial to user experience and we can do more research to better address the "delay broadcast" issue.
- remove punish delay block production
The **Intentional Delay Block Production** can be detected easily without this penalty mechanism, would prefer not to add this penalty mechanism at the moment as "delay broadcast" is quite a big topic and need more community discussion to get a more acceptable solution.

BEP-520: increase initialBackOffTime and remove punish delay block production

---

BEPs/BEP-520.md
BEPs/BEP-524.md

BEP-520: change gaslimit to 70M from 60M
based on benchmark, when block interval reduced to 1.5s, network is stable with gaslimit set to 70M

BEP-520: change gaslimit to 70M from 60M

---

BEPs/BEP-524.md

`Blob Target` and `Blob Maximum` remain unchanged to preserve compatibility with existing users

BEP-524: not change max and target of blobs in every block

---

BEPs/BEP-525.md
BEPs/BEP-536.md
README.md

"BEP-536: Directed TxPool" was withdrawn due to:
- the cons of the Directed TxPool discussed in forum
"BEP-525:Validator Dedicated Network" was withdrawn due to:
- add extra complexity to validators
- part of BEP-525 was to support BEP-536, but BEP-536 was withdrawn now
- part of BEP-525 will be replaced by "BEP-563: Enhanced Validator Network"

readme: update status of 2 BEPs

---

BEPs/BEP-563.md

This PR aims to create a more efficient network for validators. It will help to subsecond block interval.
To satisfy the network requirement of subsecond block interval, it is very helpful to have validators recognize each other in the network and be close enough to each other. Meanwhile, core consensus messages, such as Block Message and Vote Message, can be propagated under the new network topology with better network quality.
This BEP supports adding validator’s NodeID on the system contract, so the validators can identify each other in the p2p network and forward messages more efficiently.

BEP-563: add Enhanced Validator Network proposal;

---

README.md

BAP (BNB Application Proposal) defines standards for application layer interactions on BNB Chain. Unlike BEPs which govern core protocol changes, BAPs focus on establishing conventions and interfaces for how applications communicate and interact with each other within the BNB Chain ecosystem.
The process for submitting and managing BAPs follows the same standardized workflow outlined in [BEP-1:Purpose and Guidelines](https://github.com/bnb-chain/BEPs/blob/master/BEPs/BEP1.md)

workflow: add BAP(BNB Application Proposal) category
