BEP2.md
=> Fix BEP2 markdown style.

BEP10.md, BEP6.md, README.md
This PR will add the subject of every BEP in README. And change the status of BEP6&10 to `under implementation`.
=> add subject in README

BEP10.md
Claiming the identifier '5' for GoBNB app
=> Added GoBNB with '5' as identifier

BEP10.md
Register MEET.ONE source identifier 18
=> Register MEET.ONE source identifier

BEP10.md
I have edited the source discription for Safepal
=> Edit source description

BEP10.md
=> propose id for CoolBitX

BEP10.md
Please review and add Identifier number (11) for InfinifoWallet.
=> [BEP-10] Register Identifier number for InfinitoWallet.

BEP3.md, README.md
1. Add new `cross-chain` field to HTLT transaction to identify if the HTLT is for cross chain swap.
2. Add deposit HTLT transaction to interact with single chain swap
3. Rename Contract event name
=> R4R: Add swap between several bep2 tokens

BEP10.md
Update BEP10.md for Cosmostation Wallet
=> Update BEP10.md for Cosmostation Wallet

BEP10.md
BNB Browser - Metamask like wallet for BNB that is absolutely open-source
https://github.com/button-tech/BrowserBNB
https://chrome.google.com/webstore/detail/bnb-browser/eeflaanifildahldmpahjmgmgippmgne?hl=en
=> [BEP-10] - Add BNB Browser source code 

BEP10.md
This PR adds a source id (see [BEP10](https://github.com/binance-chain/BEPs/blob/master/BEP10.md) and #10) for Frontier Wallet, an all-in-one DeFi wallet with native Binance Chain support.
=> Register Frontier Wallet Source

BEP20.md
This bep proposes a standard interface(BEP20) for tokens on Binance Smart Chain.
=> BEP20: Tokens on Binance Smart Chain

BEP86.md, README.md
This BEP proposes a reward mechanism to balance the gain and risk for BSC relayers, which will attract more relayers to engage in and improve the cross chain communication robustness between BC and BSC.
=> R4R: BEP86 Dynamic Extra Incentive To BSC Relayers

BEP91.md, README.md
- [BEP-91: Increase Block Gas Ceiling for Binance Smart Chain](#bep-91-increase-block-gas-ceiling-for-binance-smart-chain)
- [4. Motivation](#4-motivation)
- [5. Specification](#5-specification)
- [6. License](#6-license)
This BEP describes a proposal for the increment of **gasceil** of BSC.
BEP-91 Proposal describes a change of BSC node configuration, and suggests Validator operators should increase the value of  the block `GasCeil`from `40000000` to `60000000`.
This BEP is a draft. 
The increasing adoption of BSC leads to a more active network. Blocks start hitting the gasceil daily. The increasing prevalence of blocks near the limit may lead to increased fees and delays in the processing of transactions in …
=> BEP91: Increase Block Gas Ceiling for Binance Smart Chain

README.md
This pr updates the readme file, to include the new added bep - BEP128.
=> [R4R] update index

BEP131.md
=> Fix file format of BEP131.md

BEP126.md
Rational:
format bep126 by following BEP1.md
=> format BEP126

README.md
=> more update on the BSC upgrade forecast 

BEP126.md
remove naturally justified setting in BEP126
=> BEP-126: remove naturally justified setting

BEP126.md
give more details about reward rules.
=> BEP126: more details about reward rules

README.md
=> chore: update readme to include un-indexed beps

BEPs/BEP322.md
remove outdated / not needed content for BEP322.
=> remove outdated content for bep322

BEPs/BEP322.md
remove invalid content in the bep322
=> remove invalid content in the bep322

BEPs/BEP-441.md
BEP-441: Implement EIP-7702: Set EOA account code
=> BEP-441: Implement EIP-7702: Set EOA account code

BEPs/BEP-496.md
BEP-496: Implement EIP-7623: Increase calldata cost;
Thanks to the authors of EIP-7623: Toni Wahrstätter (@nerolation), Vitalik Buterin (@vbuterin).
=> BEP-496: Implement EIP-7623: Increase calldata cost;

BEPs/BEP-497.md
BEP-497: Implement EIP-7691: Blob throughput increase
Thanks to the authors of EIP-7691: Parithosh Jayanthi (@parithosh), Toni Wahrstätter (@nerolation), Sam Calder-Mason (@samcm), Andrew Davis (@savid).
=> BEP-497: Implement EIP-7691: Blob throughput increase

BEPs/BEP-414.md, BEPs/BEP153.md, BEPs/BEP172.md, BEPs/BEP173.md
fix some beps for missing license
=> chore: fix license issue of some beps

BEPs/BEP-496.md, README.md
[BEP-496](https://github.com/bnb-chain/BEPs/pull/496): update latest changes;
=> BEP-496: update latest changes;

BEPs/BEP-543.md, BEPs/opBNB-shorter-block-interval.md
opBNB shorter block interval proposal
=> BEP-543: opBNB shorter block interval

BEPs/BEP-520.md, BEPs/BEP-524.md
clear minerHistory based on latest finalized blocks
=> BEP-524: clear minerHistory based on latest finalized blocks

BEPs/BEP12.md
=> BEP-12: fix minor issue

BEPs/BEP206.md
=> BEP-206: fix some typos in comment

BEPs/BEP1.md, README.md
The process for submitting and managing BAPs follows the standardized workflow outlined in [BEP-1: Purpose and Guidelines](https://github.com/bnb-chain/BEPs/blob/master/BEPs/BEP1.md). BAP numbers are assigned based on the PR number, ensuring no overlap with BEP numbers.
=> BAP: workflow description

BEPs/BEP217.md
=> BEP-217: fix typo
